branch-defaults:
  dev:
    environment: null
  deploy:
    artifact: ./www/Archive.zip
global:
  application_name: udagram-ksm-dev
  branch: null
  default_ec2_keyname: udagram.keypair
  default_platform: Node.js
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
